// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdjhaeygzdpywzrwnacx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kamhhZXlnemRweXd6cnduYWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkxMjEsImV4cCI6MjA2NTU5NTEyMX0.3NvVLKAwlJ73PwyGOfBsEAjKknK4yv0yX9vuExIX4LM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);