// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkvgfqnftfzwxkmhbftb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdmdmcW5mdGZ6d3hrbWhiZnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODI3NzYsImV4cCI6MjA2NTk1ODc3Nn0.9ronZl9ug5Iu6Dt1J8D6xXdGdeil1g0MFXGtG0X_tpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);